# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright 2026 coccinella-labs

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: deps
    groups:
      cargo-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
