# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright 2026 coccinella-labs

name: lint
description: 'Run Clippy linter and upload SARIF results'
inputs:
  toolchain:
    description: 'Rust toolchain to use'
    required: false
    default: 'stable'
runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.toolchain }}
        components: clippy

    - name: Install required cargo crates
      run: cargo install clippy-sarif sarif-fmt
      shell: bash

    - name: Run rust-clippy
      run: |
        cargo clippy \
          --all-features \
          --workspace \
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      shell: bash
      continue-on-error: true

    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: rust-clippy-results.sarif
