# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright 2026 coccinella-labs

name: Dependency Review
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.repository_owner == 'coccinella-labs'
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
