# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright 2026 coccinella-labs

name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  nightly-checks:
    name: Nightly
    permissions:
      contents: write
    uses: coccinella-labs/rust-nightly/.github/workflows/nightly.yml@main
    with:
      rust-version: stable
      test-flags: --all-features --workspace
      build-flags: --release --all-features --workspace
      run-benchmarks: false
      create-release: true
      release-tag: nightly
      release-prerelease: true
